ai:
  yda:
    framework:
      rag:
        retriever:
          filesystem:
            localDirectoryPath: /Users/dmmrch/work/IdeaProjects/yda/.data/documents
            databaseName: default
            collectionName: documents
            embeddingDimension: 1536
            username:
            password:
            host: http://localhost:19530
            openAiKey: sk-proj-eTAeDDwK4dEQY09ZQktbT3BlbkFJeaKh8oDF3sZT00LtAVnf
            openAiModel: text-embedding-3-small
      generator:
        assistant:
          openai:
            api-key: sk-proj-eTAeDDwK4dEQY09ZQktbT3BlbkFJeaKh8oDF3sZT00LtAVnf
            assistant-id: asst_9S7lP9N2n99EPept42iUjLeL

