/*
 * YDA - Open-Source Java AI Assistant.
 * Copyright (C) 2024 Love Vector OÜ <https://vector-inc.dev/>

 * This file is part of YDA.

 * YDA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * YDA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public License
 * along with YDA.  If not, see <https://www.gnu.org/licenses/>.
*/
package ai.yda.framework.rag.core.model;

import lombok.Builder;
import lombok.Getter;

/**
 * Represents a response object generated as a result of processing the request and context. The response should
 * encapsulate the output generated by the mechanism used, such as a language model, and reflect the final answer or
 * action based on the user's query and the given context.
 *
 * @author Nikita Litvinov
 * @since 0.1.0
 */
@Getter
@Builder(toBuilder = true)
public class RagResponse {

    /**
     * The result string generated by the mechanism used, such as a language model, and reflect the final answer or
     * action based on the user's query and the given context.
     */
    private final String result;

    /**
     * Constructs a new {@link RagResponse} instance with the user's query.
     *
     * @param result the result string generated based on the user's query and the given context.
     */
    public RagResponse(final String result) {
        this.result = result;
    }
}
